[build]
builder = "NIXPACKS"

[services]
  [services.main]
    name = "file-analyzer"
    start = "/opt/venv/bin/python integrations/downloader.py"
    plan = "free"

[triggers]
  [triggers.cron]
    service = "file-analyzer"
    schedule = "0 * * * *"
