"""Добавил столбеу в БД и поправил форматы

Revision ID: 0caf0259524f
Revises: 65f3c687af4a
Create Date: 2025-09-30 11:56:38.260601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caf0259524f'
down_revision: Union[str, Sequence[str], None] = '65f3c687af4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
