"""Переделал структуру Card

Revision ID: 56a936658679
Revises: e527bed8058e
Create Date: 2025-10-13 18:15:17.764482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56a936658679'
down_revision: Union[str, Sequence[str], None] = 'e527bed8058e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card_disable_history', 'disabled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('card_events_operation_id_key'), 'card_events', type_='unique')
    op.create_unique_constraint('uq_card_operation', 'card_events', ['card_id', 'operation_id'])
    op.add_column('cards', sa.Column('partner', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('kyc_status', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('cards', 'first_name')
    op.drop_column('cards', 'balance')
    op.drop_column('cards', 'last_name')
    op.drop_column('cards', 'pool_id')
    op.drop_column('cards', 'total_success_amount')
    op.drop_column('cards', 'first_success_at')
    op.drop_column('cards', 'direction')
    op.drop_column('cards', 'last_success_at')
    op.drop_column('cards', 'last_error_at')
    op.drop_column('cards', 'bakai_customer_id')
    op.drop_column('cards', 'replenishment_method')
    op.drop_column('cards', 'first_error_at')
    op.add_column('error_types', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('error_types_code_key'), 'error_types', type_='unique')
    op.create_unique_constraint(None, 'error_types', ['name'])
    op.drop_column('error_types', 'created_at')
    op.drop_column('error_types', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error_types', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('error_types', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'error_types', type_='unique')
    op.create_unique_constraint(op.f('error_types_code_key'), 'error_types', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('error_types', 'name')
    op.add_column('cards', sa.Column('first_error_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('replenishment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('bakai_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('last_error_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('last_success_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('first_success_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('total_success_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('pool_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'created_at')
    op.drop_column('cards', 'kyc_status')
    op.drop_column('cards', 'partner')
    op.drop_constraint('uq_card_operation', 'card_events', type_='unique')
    op.create_unique_constraint(op.f('card_events_operation_id_key'), 'card_events', ['operation_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('card_disable_history', 'disabled_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
