transactions:
  column: ID операции
  file_pattern: "tran"      # если имя файла содержит "tran", используем этот анализатор

kyc:
  column: user_id
  file_pattern: "kyc"               # если имя файла содержит "kyc", используем другой анализатор

conversion:
  file_pattern: "conversion"     # если имя файла содержит "conversion", используем анализатор конверсии
  columns:                        # маппинг колонок для анализа
    card: "Карта"
    status: "Статус"
    datetime: "Дата/Время создания"
    partner: "Партнер"