#conversion_config.yaml
partners:
  "HH (А-мобайл Сбер + Выплаты)":

  "HH (Амобайл Тинькофф)":

  "HH (Амобайл SBP IN ВТБ)":

  "HH (Abhsber IN) Сбер карты (116)":

  "HH (Abhsber IN + Выплаты) Тинь карты (117)":

  "HH (Абхасбер - Сбер СБП) (118)":

  "HH (Аврора Тинь)":

  "HH (Аврора Сбер)":

  "HH (Кибит Сбер)":

  "HH (Кибит Тинь)":

  "HH (Бакай Тинь)":

  "HH (Амобайл - Сбер СБП)":

  "HH Вассл (Сбер сбп) (119)":

  "HH Вассл (Тинь номер карты и сбп) (120)":

  "HH Вассл (ВТБ сбп) (121)":

pools:
  aurora: "SMS"
  a-mobile: "А-Мобайл"
  abhsber: "Abhsber"
  cibit: "Cibit"
  bakai: "BakAi"
  Vassl: "Вассл"

columns:
  card: "Карта"
  partner: "Партнер"
  status: "Статус"
  datetime: "Дата/Время создания"

valid_statuses:
  - Готов к работе
  - Активный вход