#conversion_config.yaml
partners:
  "HH (А-мобайл Сбер + Выплаты)":
    threshold: 8
    start:
  "HH (Амобайл Тинькофф)":
    threshold: 3
    start:
  "HH (Амобайл SBP IN ВТБ)":
    threshold: 8
    start:
  "HH (Abhsber IN) Тинь":
    threshold: 3
    start:
  "HH (Abhsber IN) Сбер":
    threshold: 3
    start:
  "HH (Аврора Тинь)":
    threshold: 3
    start:
  "HH (Аврора Сбер)":
    threshold: 5
    start:
  "HH (Кибит Сбер)":
    threshold: 8
    start:
  "HH (Кибит Тинь)":
    threshold: 3
    start: "23.09.2025 00:00:00" # Для примера
  "HH (Бакай Тинь)":
    threshold: 3
    start:
  "HH (Амобайл - Сбер СБП) (118)":
    threshold: 8
    start:
  "HH (Abhsber IN + Выплаты) Тинь":
    threshold: 3
    start:

pools:
  aurora: "Пул SMS"
  a-mobile: "Пул А-Мобайл"
  abhsber: "Пул Abhsber"
  cibit: "Пул Cibit"
  bakai: "Пул BakAi"

columns:
  card: "Карта"
  partner: "Партнер"
  status: "Статус"
  datetime: "Дата/Время создания"

valid_statuses:
  - Готов к работе
  - Активный вход