# Трафик-Мониторинг
# HOURLY REPORT CONFIG
# ===========================================================

# -------------------------
# PAYOUT (Выплаты)
# -------------------------
# Структура:
# payout:
#   "<оригинальное имя партнёра из PayOut>":
#       <метод>:
#           title: "<как писать в отчёте>"
#           limit: <число или null>
#           vilka: "<текст вилки или null>"

payout:

  "HH (А-мобайл Сбер + Выплаты) (107)":
    title: "А-мобайл"
    methods:
      UNI:
        title: "UNI"
        comment: "(Лимит 4кк - круглосуточно , вилка до 100к)"
      BST:
        title: "BST"
        comment: "(на стопе)"

  "HH (Abhsber IN) Сбер  (116)":
    title: "АБХСбер (116)"
    methods:
      "":
        title: "UNI"
        comment: "(Лимит 8кк - круглосуточно , вилка 5-100к)"

# --------------------------
# PAYOUT LAYOUT (ГРУППЫ И ОТСТУПЫ)
# --------------------------
# spacing = количество пустых строк после группы

payout_layout:

  - group:
      - "А-мобайл"
    spacing: 1

  - group:
      - "АБХСбер (116)"
    spacing: 0


# -------------------------
# PAYIN (Одиночные)
# -------------------------
# Структура:
# payin:
#   "<оригинальное имя партнёра из PayIn>":
#       title: "<как писать в отчёте>"
#       limit: <число или null>
#       vilka: "<текст или null>"

payin:

  "HH (А-мобайл Сбер + Выплаты) (107)":
    title: "Амобайл Сбер (107)"
    comment: "(Лимит 4 КК)"

  "HH (А-мобайл Тинь) (113)":
    title: "Амобайл Тинь (113)"
    comment: "(на стопе)"

  "HH (Кибит Сбер) (111)":
    title: "Кибит Сбер (111)"
    comment: "(Лимит 15  КК Вилка СТРОГО до 50 К)"

  "HH (Аврора Сбер) (109)":
    title: "Аврора Сбер (109)"
    comment:

  "HH (Аврора Тинь) (108)":
    title: "Аврора Тинь (108)"
    comment:

  "HH (Abhsber IN) Сбер (116)":
    title: "АБХСбер Сбер (116)"
    comment:

  "HH (Abhsber IN + Выплаты) Тинь (117)":
    title: "АБХСбер Тинь (117)"
    comment:

  "HH (Абхасбер - Сбер СБП) (118)":
    title: "АБХСбер Сбер СБП (118)"
    comment:  "(Лимит 1кк 8:00-00:00)" #  2 пробела

  "HH (Бакай Тинь) (110)":
    title: "Бакай Тинь (110)"
    comment: "(Лимит 5  КК)"

  "HH Вассл (Тинь номер карты и сбп) (120)":
    title: "Вассл Тинь номер карты и сбп (120)"
    comment: "(Лимит 500 К - круглосуточно)"

# -------------------------
# PAYIN GROUPS (суммарные)
# ---------------------------
# Структура:
# payin_groups:
#   <код группы>:
#       title: "<как писать в отчёте>"
#       combine:
#         - "<оригинальное имя партнера 1>"
#         - "<оригинальное имя партнера 2>"
#       limit: <число или null>
#       vilka: "<текст или null>"

payin_groups:

  abhsber_sum:
    title: "АБХСбер (116 + 117)"
    combine:
      - "HH (Abhsber IN) Сбер (116)"
      - "HH (Abhsber IN + Выплаты) Тинь (117)"
    comment: "(Лимит 8,5  КК)"

  aurora_sum:
    title: "Аврора (108 + 109)"
    combine:
      - "HH (Аврора Сбер) (109)"
      - "HH (Аврора Тинь) (108)"
    comment: "(Лимит 8 КК)"


# --------------------------
# PAYIN LAYOUT
# --------------------------
# Формат подписей, как в title:
# payin:
# payin_groups:

payin_layout:

  - group:
      - "Амобайл Сбер (107)"
      - "Амобайл Тинь (113)"
    spacing: 1

  - group:
      - "Кибит Сбер (111)"
    spacing: 1

  - group:
      - "Аврора Сбер (109)"
      - "Аврора Тинь (108)"
      - "Аврора (108 + 109)"
    spacing: 1

  - group:
      - "АБХСбер Сбер (116)"
      - "АБХСбер Тинь (117)"
      - "АБХСбер (116 + 117)"
    spacing: 1

  - group:
      - "АБХСбер Сбер СБП (118)"
    spacing: 1

  - group:
      - "Бакай Тинь (110)"
    spacing: 1

  - group:
      - "Вассл Тинь номер карты и сбп (120)"
    spacing: 0