# ==========================
# PAYOUT (ВЫПЛАТЫ)
# ==========================

payout:
  Амобайл:
    UNI:
      limit: 5000000
      vilka: "до 100К"
    BST:
      limit: 0
      vilka: "на стопе КК"

  АБХСбер:
    UNI:
      limit: 5000000
      vilka: "5–100К"


# ==========================
# PAYIN (ПОСТУПЛЕНИЯ)
# ==========================

payin:
  Амобайл:
    "107 терминал Сбер":
      match: ["амобайл", "107", "сбер"]

    "113 терминал Тинь":
      match: ["амобайл", "113", "тинь"]

  Кибит:
    "Кибит":
      match: ["кибит"]

  Аврора:
    "Аврора 108 терминал Тинь":
      match: ["аврора", "108", "тинь"]
    "Аврора 109 терминал Сбер":
      match: ["аврора", "109", "сбер"]

    "Аврора 108+109 суммарно":
      combine:
        - "Аврора 108 терминал Тинь"
        - "Аврора 109 терминал Сбер"

  АБХСбер:
    "116 терминал Сбер":
      match: ["абх", "116", "сбер"]
    "117 терминал Тинь":
      match: ["абх", "117", "тинь"]

    "116+117 суммарно":
      combine:
        - "116 терминал Сбер"
        - "117 терминал Тинь"

  Бакай:
    "110 терминал Тинь":
      match: ["бакай", "110", "тинь"]
