# ===========================================================
# HOURLY REPORT CONFIG
# ===========================================================

# -------------------------
# PAYOUT (Выплаты)
# -------------------------
# Структура:
# payout:
#   "<оригинальное имя партнёра из PayOut>":
#       <метод>:
#           title: "<как писать в отчёте>"
#           limit: <число или null>
#           vilka: "<текст вилки или null>"

payout:

  "HH (А-мобайл Сбер + Выплаты) (107)":
    UNI:
      title: "UNI"
      limit: 5000000
      vilka: "ДО 100 К"
    BST:
      title: "BST"
      limit: null
      vilka: "на стопе КК"

  "HH (Abhsber IN + Выплаты) Тинь (117)":
    UNI:
      title: "UNI"
      limit: 5000000
      vilka: "5–100 К"


# -------------------------
# PAYIN (Одиночные)
# -------------------------
# Структура:
# payin:
#   "<оригинальное имя партнёра из PayIn>":
#       title: "<как писать в отчёте>"
#       limit: <число или null>
#       vilka: "<текст или null>"

payin:

  "HH (А-мобайл Сбер + Выплаты) (107)":
    title: "Амобайл 107 терминал Сбер"
    limit: 2200000
    vilka: null

  "HH (А-мобайл Тинь) (113)":
    title: "Амобайл 113 терминал Тинь"
    limit: null
    vilka: "на стопе"

  "HH (Кибит Сбер) (111)":
    title: "Кибит"
    limit: 15000000
    vilka: "СТРОГО до 50 К"

  "HH (Аврора Сбер) (109)":
    title: "Аврора 109 терминал Сбер"
    limit: null
    vilka: null

  "HH (Аврора Тинь) (108)":
    title: "Аврора 108 терминал Тинь"
    limit: null
    vilka: null

  "HH (Abhsber IN) Сбер (116)":
    title: "АБХСбер 116 терминал Сбер"
    limit: null
    vilka: null

  "HH (Abhsber IN + Выплаты) Тинь (117)":
    title: "АБХСбер 117 терминал Тинь"
    limit: null
    vilka: null

  "HH (Абхасбер - Сбер СБП) (118)":
    title: "АБХСбер 118 терминал Сбер"
    limit: 230000       # 230 К
    vilka: null

  "HH (Бакай Тинь) (110)":
    title: "Бакай 110 терминал Тинь"
    limit: 5000000
    vilka: null


# -------------------------
# PAYIN GROUPS (суммарные)
# -------------------------
# Структура:
# payin_groups:
#   <код группы>:
#       title: "<как писать в отчёте>"
#       combine:
#         - "<оригинальное имя партнера 1>"
#         - "<оригинальное имя партнера 2>"
#       limit: <число или null>
#       vilka: "<текст или null>"

payin_groups:

  abhsber_sum:
    title: "АБХСбер 116 + 117 суммарно"
    combine:
      - "HH (Abhsber IN) Сбер (116)"
      - "HH (Abhsber IN + Выплаты) Тинь (117)"
    limit: 8000000       # 8 КК
    vilka: null

  aurora_sum:
    title: "Аврора 109 + 108 суммарно"
    combine:
      - "HH (Аврора Сбер) (109)"
      - "HH (Аврора Тинь) (108)"
    limit: 5000000       # 5 КК
    vilka: null
