# config/payout_config.yaml

PayoutsErrors:
  # пример: фраза из столбца Info и порог подряд идущих ошибок
  "Unistream_1":
    threshold: 1
  "Unistream_2":
    threshold: 1
  "ORA-20001":
    threshold: 2
  "ограничения законодательства - уровень идентификации денежных средств недостаточен":
    threshold: 3
  "код возврата: i07999. ошибка":
    threshold: 3
  "код возврата: i05038. ограничения законодательства - уровень идентификации денежных средств недостаточен":
    threshold: 3
  "операция отклонена":
    threshold: 3


IgnoreErrors:
  # сюда заносим фразы Info, которые полностью игнорируем

  - "код возврата: i05043. отказ от банка получателя"
  - "код возврата: i01091. нет ответа. таймаут"
  - "ошибка внешней системы.: (код возврата: i05043. отказ от банка получателя)"
  - "[b2c] d02 timeout"
  - "код возврата: i05034. подозрительная активность в отношении получателя"
