# config/payout_config.yaml

PayoutsErrors:
  # пример: фраза из столбца Info и порог подряд идущих ошибок
  "ORA-20001: Sbp Members НЕ найден в базе":
    threshold: 1
  "Ошибка проверки Unistream_2: Unistream API Error: 404 Client Error":
    threshold: 1
  "Ошибка проверки Unistream_1: Unistream API Error: 406 Client Error":
    threshold: 1
  "ограничения законодательства - уровень идентификации денежных средств недостаточен":
    threshold: 7
  "операция отклонена":
    threshold: 7
  "операция отменена":
    threshold: 7
  "ошибка внешней системы.: (перевод не может быть осуществлен)":
    threshold: 7
  "ошибка создания":
    threshold: 5
  "возникла техническая ошибка (-1). обратитесь в контакт-центр 777-77-77.":
    threshold: 5





IgnoreErrors:
  # сюда заносим фразы Info, которые полностью игнорируем

  - "код возврата: i05043. отказ от банка получателя"
  - "код возврата: i01091. нет ответа. таймаут"
  - "ошибка внешней системы.: (код возврата: i05043. отказ от банка получателя)"
  - "[b2c] d02 timeout"
  - "код возврата: i05034. подозрительная активность в отношении получателя"
