#conversion_config.yaml

partners:
  "Hedge Hog (А-мобайл Сбер +Выплаты)": 8
  "Hedge Hog (Амобайл Тинькофф)": 3
  "Hedge Hog (Амобайл SBP IN ВТБ)": 5
  "Hedge Hog (Abhsber IN) Тинь": 3
  "Hedge Hog (Abhsber IN) Сбер": 8
  "Hedge Hog (Аврора Тинь)": 3
  "Hedge Hog (Аврора Сбер)": 8
  "Hedge Hog (Кибит Сбер)": 8
  "Hedge Hog (Кибит Тинь)": 3
  "Hedge Hog (Бакай Тинь)": 3



pools:
  aurora: "Пул SMS"
  a-mobile: "Пул А-Мобайл"
  abhsber: "Пул Abhsber"
  cibit: "Пул Cibit"
  bakai: "Пул BakAi"
